FROM amazeeio/logstash

RUN bin/logstash-plugin install logstash-input-lumberjack

# Remove default shipped pipeline
RUN rm -f pipeline/logstash.conf

COPY pipeline/router-application-logs.conf pipeline/router-application-logs.conf
COPY templates/application-logs.json templates/application-logs.json
COPY templates/router-logs.json templates/router-logs.json
COPY certs/ certs/

RUN echo $'\n\
- pipeline.id: router-application-logs\n\
  path.config: "pipeline/router-application-logs.conf"' >> pipelines.yml

# https://github.com/elastic/logstash-docker/issues/64
ENV PATH_CONFIG=null

ENV ELASTICSEARCH_URL="http://logs-db:9200" \
    LOGSDB_PASSWORD=admin \
    LOGSDB_USERNAME=admin \
    XPACK_MANAGEMENT_ENABLED=false \
    XPACK_MONITORING_ENABLED=false

